---
- hosts: all_production_hosts
  tasks:
  - name: Install curl
    apt: pkg=curl state=present force=yes

  - name: Fetch docker.
    shell: export https_proxy=http://XX.XX.XX.XX:XXXX && cd /usr/local/src && wget -qO- https://get.docker.com/ -e use_proxy=yes -e https_proxy=XX.XX.XX.XX:XXXX | sh

#  - name: Add possibility to use Docker as a non-root user.
#    shell: usermod -aG docker your-user